### ISSUE TITLE
Idea about playing movies

### ISSUE THREAD

**Issue by marcelkorpel** [kubi2021/plugin.video.mubi#2]
In case you haven't found this already, please have a look at the way [this fork](https://github.com/flxapps/plugin.video.mubi) uses [inputstream.adaptive](https://github.com/peak3d/inputstream.adaptive) to play movies. It worked fine in Kodi 18. I'm not that well-versed in Python, so I'm not able to provide a pull request, but perhaps you (or someone else) can take inspiration from there.

**Comment by kubi2021** [comment]
I'm thrilled to announce that the addon now supports playing movies directly within MUBI! 🎉
What's New

- Direct Playback: You can now enjoy MUBI films directly through the addon without needing to open them in an external web browser.
- Subtitle Support: Multiple subtitle languages are available, enhancing your viewing experience.
- Library Integration: Sync all MUBI films locally and play them directly from your Kodi library.
