### ISSUE TITLE
abandoned? 

### ISSUE THREAD

**Issue by slynobody** [kubi2021/plugin.video.mubi#3]
if the world needs something it would be a working mubi-addon for kodi. at least for the current version.

is this abandoned? could you please, please, please update the addon?

**Comment by zuzia-dev** [comment]
A working plug-in for MUBI is in the repository: https://github.com/mtr81/kodi_addons

**Comment by kubi2021** [comment]
Hello, sorry for the delay. I just updated the Addon, it should work like it did before.
